# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 437)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browser = QtWidgets.QPushButton(self.centralwidget)
        self.browser.setGeometry(QtCore.QRect(260, 10, 71, 31))
        self.browser.setObjectName("browser")
        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(26, 52, 571, 331))
        self.screen.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.screen.setText("")
        self.screen.setScaledContents(True)
        self.screen.setObjectName("screen")
        self.check_box = QtWidgets.QComboBox(self.centralwidget)
        self.check_box.setGeometry(QtCore.QRect(470, 10, 121, 31))
        self.check_box.setObjectName("check_box")
        self.check_box.addItem("")
        self.check_box.addItem("")
        self.check_box.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.line_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.line_Edit.setGeometry(QtCore.QRect(30, 10, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.line_Edit.setFont(font)
        self.line_Edit.setObjectName("line_Edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 626, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browser.setText(_translate("MainWindow", "Browser"))
        self.check_box.setItemText(0, _translate("MainWindow", "None"))
        self.check_box.setItemText(1, _translate("MainWindow", "Bộ lọc thời gian"))
        self.check_box.setItemText(2, _translate("MainWindow", "Bộ lọc tần số"))
        self.label_2.setText(_translate("MainWindow", "Chọn bộ lọc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
